version: "3"

services: 

    server:
        build: .
        ports:
            - 5000:5000
        volumes:
            - ./dailynotes-volume:/app/config
        environment: 
            API_SECRET_KEY: CHANGE_THIS_WITH_SECURE_PASSWORD
            DB_ENCRYPTION_KEY: CHANGE_THIS_WITH_SECURE_PASSWORD